### ISSUE TITLE
'NoneType is not callable' on get_assignments

### ISSUE THREAD

**Issue by swgillespie** [swgillespie/tsquare#1]
Stack trace from heroku:

```
2013-11-01T18:36:04.283363+00:00 app[web.1]: Internal Server Error: /list_assignments/
2013-11-01T18:36:04.283363+00:00 app[web.1]:   File "/app/tsquare-web/views.py", line 112, in list_assignments
2013-11-01T18:36:04.283363+00:00 app[web.1]: Traceback (most recent call last):
2013-11-01T18:36:04.283363+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
2013-11-01T18:36:04.283363+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2013-11-01T18:36:04.283363+00:00 app[web.1]:     return func(self, *args, **kwargs)
2013-11-01T18:36:04.283363+00:00 app[web.1]:     response = callback(request, *callback_args, **callback_kwargs)
2013-11-01T18:36:04.283363+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
2013-11-01T18:36:04.283601+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/tsquare/parsers.py", line 50, in get_assignments
2013-11-01T18:36:04.283363+00:00 app[web.1]:     assignments.append(tsapi.get_assignments(s))
2013-11-01T18:36:04.283363+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/tsquare/core.py", line 43, in _auth
2013-11-01T18:36:04.283601+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/tsquare/core.py", line 192, in get_assignments
2013-11-01T18:36:04.283601+00:00 app[web.1]:     for i, table_row in enumerate(table('tr')):
2013-11-01T18:36:04.283601+00:00 app[web.1]:     assignment_dict_list = self._html_iface.get_assignments(response.text)
2013-11-01T18:36:04.283601+00:00 app[web.1]: TypeError: 'NoneType' object is not callable
```

**Comment by swgillespie** [comment]
Things to investigate:

1) Table may not be callable because doc.table is null. Handle this error gracefully?
2) ) get_assignments isn't getting set correctly?

Most likely 1.
